### ISSUE TITLE
Linclusts all_seqs is not a proper FASTA file

### ISSUE THREAD

**Issue by jakobnissen** [soedinglab/MMseqs2#114]
## Expected Behavior
Linclust's all_seqs.fasta should create a valid FASTA file. 

## Current Behavior
Currently, the header of representative sequences are printed twice, like this:

```
>repr_seq
>repr_seq more stuff in the header
[sequence]
>another_seq
[sequence]
```

## Steps to Reproduce (for bugs)
1) Run the tutorial for the ECCB2018 tutorial until after the very first Linclust call.
2) Run "head -2 clusteredProts.faa_all_seqs.fasta"

**Comment by fstrozzi** [comment]
@martin-steinegger a related question. Using the latest release 5-9375b (the precompiled AVX2 binaries to be precise), I have seen that the *_req_seq.fasta file that is created is also not a proper Fasta file. Instead of having the aminoacid sequences of the representatives, I have the sequences IDs, like this 

```
>sequence_1
sequence_1
>sequence_2
sequence_2
```

Is it a bug ? 

Thanks!

**Comment by martin-steinegger** [comment]
@jakobnissen @fstrozzi  Can I close this issue?

**Comment by jakobnissen** [comment]
@martin-steinegger Yes, please do.
