### ISSUE TITLE
Get cluster sequence identities

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/mmseqs2#13]
Hi,
thank you very much for mmseqs2, it's really amazing! 

We are clustering a few million of sequences following a similar approach than the one described in your uniclust pipeline. Before reinventing the wheel, we are wondering if mmseqs has an easy workaround to extract the sequence identities for each pair of sequences in a cluster from the _alignment_ file. Our aim would be to be able to integrate the identities between pairs to the output of _createtsv_. Do you have any recommendations?

Many thanks
Antonio

**Comment by milot-mirdita** [comment]
Hi Antonio,

You can do something like this:

```
mmseqs cluster db clu tmp
mmseqs align db db clu aln -a
mmseqs createtsv  db db aln aln.tsv
```

The `-a` parameter computes the whole backtrace, you can also use `--alignment-mode 3`, but that computes the backtrace anyway since it needs it for the seq. id. 
`--alignment-mode` 1 and 2 only approximate the sequence identity.

Thank you for the feedback! We will add this to the FAQ and also discuss if it make sense to provide the same output also for Uniclust in future releases.

**Comment by genomewalker** [comment]
Thank you very much! I will give it a try tonight and be back to you. 

>  We will add this to the FAQ and also discuss if it make sense to provide the same output also for Uniclust in future releases.

In our case, this information will help us to evaluate the quality of the clusters.

Cheers
Antonio

**Comment by milot-mirdita** [comment]
One more possible problem: the default `--max-seqs` is too low for this task. You should set it to some very large number (`--max-seqs 2147483647`). So you will get every sequence identity of every cluster member.

**Comment by genomewalker** [comment]
Hi Milot,
I did a quick look to the results and seems that it work perfectly. I will have more a more thorough look to the results in case we are missing any pair.
Many thanks

Cheers
Antonio
