### ISSUE TITLE
Add taxonomic and function informations into the .m8 output file. 

### ISSUE THREAD

**Issue by Grindell** [soedinglab/MMseqs2#166]
Hi everyone, I ran a `mmseqs search` and a `convertalis `run in order to get a .m8 output format.

I would like to add more informations into this` .m8 `file by adding taxonomy, function, familly etc names of each hit in my file.

The accessions number are from NCBI
and the `mmseqs2_db.lookup `file looks like:

```
0	YP_008004056.1	0
1	YP_009304977.1	0
2	YP_004063493.1	0
3	YP_003457306.1	0
4	NP_076520.1	0
5	YP_009361849.1	0
```
etc 

Do you know if the `mmseqs taxonomy` will work for such a thing? 

Thank you for your help.

**Comment by milot-mirdita** [comment]
The `taxonomy` workflow is usable for your use case, but still under construction to make it user friendly. Building taxonomy databases is still not straightforward, however, this will change in the next few weeks.

However, we have only tested taxonomic annotations based on the UniProt KB. If you generate a mapping between a NCBI accession and its NCBI taxonomy identifier, you should be able to build an MMseqs2 taxonomy database, but we haven't done that yet ourselves.

Also the `taxonomy` workflow requires to run [two additional searches](https://github.com/soedinglab/MMseqs2/wiki#taxonomy-assignment-using-mmseqs-taxonomy). The second search is quite an expensive operation, since it requires high sensitivity searches against a large database.

**Comment by Grindell** [comment]
Ok thank you for all these useful informations.

**Comment by martin-steinegger** [comment]
@fbreitwieser wrote a guide how to turn a NCBI BLAST database into a mmseqs taxonomy datebase. https://github.com/soedinglab/MMseqs2/wiki#create-a-sequence-database-with-taxonomic-information-from-an-existing-blast-database
