### ISSUE TITLE
Sequence db size != result db size

### ISSUE THREAD

**Issue by simeonborko** [soedinglab/MMseqs2#186]
## Expected Behavior

I need to run easy-cluster.

## Current Behavior

 With some combinations of set of sequences and min-seq-id parameter, easy-cluster fails. It seems another condition is that both tmpDir and prefix are given by absolute path.

## Steps to Reproduce (for bugs)
Get this file and save it as `seqs.fa`: https://gist.github.com/simeonborko/3557ebfd417e4ff2033a3f41558d3254
Run:
```
mmseqs easy-cluster --min-seq-id 0.2 seqs.fa /tmp/cl /tmp/temp
```

## MMseqs Output (for bugs)

```
Sequence db size != result db size
Error: Pre-clustering step died
Error: linclust died
Error: Search died
```

## Your Environment

* mmseqs version: 034bb1bcb6a2a8c2850854b33085ba88f0cab2ef
* OS: Ubuntu 18.04
* mmseqs static build sse4.1

**Comment by milot-mirdita** [comment]
Could you please try to reproduce the issue with the latest MMseqs2 release? Your build is quite old the issue might have already been fixed in the meantime.

Please try this release: https://github.com/soedinglab/MMseqs2/releases/tag/8-fac81
We were able to execute your example successfully with it.

**Comment by simeonborko** [comment]
Good idea! :) It seems to be fixed. Thanks.
