### ISSUE TITLE
[feature request] mmseqs prefilter missing option 

### ISSUE THREAD

**Issue by jhcepas** [soedinglab/MMseqs2#22]
The following options (available in `mmseqs search` but not in `mmseqs prefilter`) would be extremely useful when running a prefilter analysis:
```
-e                 evalue cut-off
--max-accept       max number of hits to report (currently all matches are reported creating very big files)
--start-sens       start sensitivity
--sens-step-size   sensitivity step sizes
```

**Comment by martin-steinegger** [comment]
Do you still use the prefilter as alignment replacement?

**Comment by jhcepas** [comment]
hi @martin-steinegger. only for tests.... I would need the same filtering options, cascading clustering, and parseable outputs.

**Comment by martin-steinegger** [comment]
@jhcepas you can use `--alignment-mode 4` now to do your wanted operations. 
This feature works since commit https://github.com/soedinglab/MMseqs2/commit/04f86023b2eb20d41c70be2bf6d0157daea8d9c2. 

This mode calls the `prefilter` followed by the `rescorediagonal` module. So it is way faster compared to the smith waterman alignment. Please let me know if you encounter any problems with it.

**Comment by jhcepas** [comment]
that's wonderful news, thanks!
If I understood correctly the clustering algorithm, using alignment-mode 4 should not impact much the quality of the clusters, right?

**Comment by martin-steinegger** [comment]
@jhcepas yes the quality should be the same.
