### ISSUE TITLE
Huge "core" file created

### ISSUE THREAD

**Issue by Guillaume-Marseille** [soedinglab/MMseqs2#257]
Hello

I am running MMSEQS through the SLURM job scheduler on our institute cluster.

In the mmseqs SEARCH command line of my SLURM script, I specify a temporary directory on the /tmp of the compute node. However, during execution, I have a file named like "core.181135" which is created and which reaches a phenomenal size (>400GB) in the folder where my slurm script is located and from where I launch the sbatch command. The "181135" number corresponds to the process id of the mmseqs job on the compute node.

I was wondering if anyone around here could have any idea of the origin of this bizarre behavior of the program.

The command line is like (I also attach the SLURM script to this post):

`mmseqs search /shared/projects/phycovir/JGI/MMSEQS/ScafRef-ALLDATES.COASSEMBLY.lgmin2000.pep.mms /shared/bank/nr/current/mmseqs/nr.mmdb /shared/projects/phycovir/JGI/MMSEQS/NR/ScafRef-ALLDATES.COASSEMBLY.lgmin2000.pep_VS_nr.mms.rsltDB /tmp/tmp_mmseqs.181126 --remove-tmp-files true --threads 64 -a -e 1E-5 -v 3`

I hope it's clear enough
Thanks for the help
Guillaume

## Your Environment
mmseqs2/10-6d92c

[MMSEQ-SEARCH-69.SLURM.txt](https://github.com/soedinglab/MMseqs2/files/3956903/MMSEQ-SEARCH-69.SLURM.txt)

**Comment by martin-steinegger** [comment]
We do not have any code in mmseqs2 that writes this core dump file. This is a feature of Linux. Core dumps can be deactivated in Linux using ulimit -c 0 (see https://linux-audit.com/understand-and-configure-core-dumps-work-on-linux/). 

Normally a core dump occurs because the software crashes. Did you see that MMseqs2 ended with a seg. fault? 

If you want a set of stickers though (see https://twitter.com/thesteinegger/status/1201076220957315074), sent me your address via mail.

**Comment by martin-steinegger** [comment]
@Guillaume-Marseille is there any update on this issues?

**Comment by Guillaume-Marseille** [comment]
Oops I forgot to give an update on this issue.

Actually, the problem was related to a bad indexing of the database. Once the formatting and indexing were fully redone, everything started working again properly.

So it was on my side that the problem occurred. 

I'm sorry to have bothered you unnecessarily.

Thank you again for the help

Meilleurs voeux
Guillaume
