### ISSUE TITLE
nident is always equal to 0

### ISSUE THREAD

**Issue by jgugliel** [soedinglab/MMseqs2#288]
## Expected Behavior
nident should be greater than 0 and vary between hits.

## Current Behavior
nident is always equal to 0 even for exact matches.

## Steps to Reproduce (for bugs)
I used this proteome for testing: https://www.ncbi.nlm.nih.gov/protein?LinkName=nuccore_protein&from_uid=983357513

mmseqs createdb codi.fasta codiDB
mmseqs createindex --threads 6 codiDB .
mmseqs search --threads 6 codiDB codiDB resultDB . -s 1
mmseqs convertalis codiDB codiDB resultDB codi.out --format-output "query,target,nident,pident,qlen,tlen,qcov,tcov,evalue"

## Context
I observe the same behavior on our HPC with version 11-e1a1c (self-compiled, I guess) and on my Mac with version 10.6d92c (miniconda)

**Comment by milot-mirdita** [comment]
You need to pass `-a` to `search` to compute and store full alignments. Without that option `convertalis` will not be able to compute identical matches and a few more.

It should have warned you that it needs this parameter, I’ll fix the missing warning later.

If you want a set of stickers (see https://twitter.com/thesteinegger/status/1201076220957315074), send me your address to milot at mirdita de (might take a while though due to current circumstances).

**Comment by jgugliel** [comment]
I was sure I was missing something quite simple.
Thanks a lot for your quick reply and have a nice week-end (despite the circumstances).
