### ISSUE TITLE
Combine output files 

### ISSUE THREAD

**Issue by linsalrob** [soedinglab/MMseqs2#292]
## Expected Behavior
When running a command on a machine with multiple cores, all the output files should be combined into a single final results file.

## Current Behavior
All the files are numbered `1` to `n` where `n` is the number of cores. 

## Steps to Reproduce (for bugs)
This happens with many commands (e.g. `mmseqs cluster` `mmseqs lca`, `mmseqs taxonomy`, etc)

## Context
Each file is numbered individually, but a better output would be to combine all outputs to a single file. 

A trivial solution is to add `--threads 1` to the command, but that seems to be anti-use-case.

The number of files is dependent on the number of cores. `cat results.? results.??  > results` is a trivial solution, but clumsy to implement for every `mmseqs` call in a pipeline.

In addition, the current `mmseqs` solution doesn't work well with (for e.g.) `snakemake` that is expecting specific files.

## Your Environment
MMseqs2 Version: c75fe9acf701d9dee97b68dcbbda92fa7b1fc2de
Running on CentOS 8.

**Comment by martin-steinegger** [comment]
@linsalrob Thanks for opening this issue. I am not very familiar with snakemake but we intentionally do not produce a single file with these modules since this would cost extra IO and slow down the software. Why do you need exactly one output file? The modules that produce output for consumption by other software (e.g. `convertalis`) already produce single files. As a workaround for your Snakemake issue, you can check if a process was successfully by checking if the `.dbtype` file exists.

If you want a set of stickers (see https://twitter.com/thesteinegger/status/1201076220957315074), send your address to themartinsteinegger gmail com

**Comment by linsalrob** [comment]
That seems quite reasonable. Ah, yes, it looks like there is always a `.dbtype` and a `.index` file. Do all the `mmseqs` commands produce those files?

**Comment by martin-steinegger** [comment]
Yes they should produce it.

**Comment by linsalrob** [comment]
Thanks, Martin! Closed.
