### ISSUE TITLE
Merge SeqTaxDBs

### ISSUE THREAD

**Issue by Abonacolta** [soedinglab/MMseqs2#302]
I was wondering how I could merge existing SeqTaxDBs into one database? Also is it possible to add sequences, individually, to this database as well? For instance, I would like to create an updated version of the MMETSP_zenodo_3247846_uniclust90_2018_08_seed_valid_taxids DB used in the MetaEuk paper, then add my model organism to the final database.

**Comment by elileka** [comment]
I principle, you should be able to merge two older SeqTaxDbs into one using ```concatdbs``` but there are two things to look out for:

1. that the DBs are not too old. That is, they have _mapping, .lookup and .source files associated with them.

2. that the two DBs were originally associated with the same version of NCBI taxonomy [taxdump.tar.gz](ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz). This is very important because at the end of the merge you will copy one set of the NCBI files to be the set associated with the merged database (this is not done by ```concatdbs```) and if there are inconsistencies in deleted NCBI nodes, etc., it can be a bit painful.

This mean that you will need to create a SeqTaxDb from the sequences of your own organism. You can read how in the taxonomy wiki section and specifically in [this](https://github.com/soedinglab/MMseqs2/wiki#creating-a-seqtaxdb) and [this](https://github.com/soedinglab/MMseqs2/wiki#create-a-seqtaxdb-by-manual-annotation-of-a-sequence-database) parts of it.

I should say that MMseqs2 provides quite nice support for converting sequence databases with Uniprot IDs to SeqTaxDbs but it's a bit more involved to convert a non-conventional database (such as the MMETSP resource used for the MetaEuk paper). If you encounter difficulties, please write us again. We will try to help and also improve instructions if needed.

Good luck!

**Comment by Abonacolta** [comment]
Thanks!
