### ISSUE TITLE
Compute alignment once

### ISSUE THREAD

**Issue by acpguedes** [soedinglab/MMseqs2#308]
Hi,

Imagining I want to perform a hierarchical cluster manually.  
The common steps are: 
1- create a sequence DB `createdb`; 
2- create prefilter `prefilter`; 
3- perform alignments `align`; 
4- perform cluster `clust`; 
5- subset the representatives `createsubdb`; 
6- repeat everything changing the parameters.

I had a few questions about this:
1- Am I doing right the cluster?
2- I want to hierarchically cluster, for example, at 90% identity, 60%, and at least 30%. 
     - If I perform the alignment for 30% identity, can I use `apply` to build an alignment DB to the results to create a subset with different criteria? This way I must run `mmseqs align` only once. 
3- Since one sequence DB is a subset from another, when I perform `createsubdb` will I get a new DB or just the subset index to the original DB? I mean, how the disk usage increase to each subset? 

Thanks a lot.

**Comment by milot-mirdita** [comment]
1) Sounds about right. You still need to merge all clusterings in the end with `mergeclusters` (careful about the order of the input clusterings). Also keep in mind that the `cluster` workflow also has a reassignment stage since some time that is more involved to emulate (if you need something like that).
2) You should use `filterdb` `--filter-column` + `--comparison-operator` + `--comparison-value`. It's a lot faster than `apply`.
However, I am not sure this approach is actually faster. Doing a low sensitivity clustering at 90% first and then taking all representatives and clustering at 50% is a lot faster than clustering at 50% directly and then reconstructing the 90% step.
3. Createsubdb will depending on `--subdb-mode` either only write a new `.index` and symlink the data, or write only the selected entries (+ their respective index entry). The headers are currently always symlinked.

**Comment by acpguedes** [comment]
Thanks @milot-mirdita 

I'll compare the speed between the strategy with `filter` and the clustering each step with representatives from the previous cluster.

If you like I may report the results.

thanks
