### ISSUE TITLE
NR taxonomy data

### ISSUE THREAD

**Issue by MeggyC** [soedinglab/MMseqs2#352]
## Expected Behavior
Hey! I've been trying to manually download and link the taxonomy files from NCBI to the NR database that I have downloaded.

## Current Behavior
I cannot compile the taxonomy of the NR db - the documentation shows how to for NT so I tried to convert that example code to something suitable for NR (nt replaced with nr and .fna replaced with .faa)
- see  MMseqs Output (for bugs) attached file for errors 

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

```
wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
mkdir taxonomy && tar -xxvf taxdump.tar.gz -C taxonomy

```
`
blastdbcmd -db nr -entry all > nr.faa`
First error occurs here

```
blastdbcmd -db nr -entry all -outfmt "%a %T" > nr.faa.taxidmapping

mmseqs createdb nr.faa nr.faaDB


```
Second error occurs here - I was then going to continue with: 

`mmseqs createtaxdb nr.faaDB tmp --ncbi-tax-dump taxonomy/ --tax-mapping-file nt.faa.taxidmap`

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.
[mmseqstaxonomyerror22092020.txt](https://github.com/soedinglab/MMseqs2/files/5259261/mmseqstaxonomyerror22092020.txt)

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Ran in a conda environment on mmseqs version 2.12

**Comment by milot-mirdita** [comment]
It looks like multiple downloads have failed before you the MMseqs2 calls. I would recommend downloading the files again (taxdump and also recreating the NR fasta) and try again.

However, I am not sure how well this procedure will work at all since I think something  in the the blast database format has changed and the `blastdbcmd` might run into issues.

The NR is now also available in our `databases` workflow you can let MMseqs2 download the NR and create all the associated taxonomy files. The latest git MMseqs2 also has a a faster version with a few more kinks ironed out (you can download binaries at https://mmseqs.com/latest).

The call for that would be:
```
mmseqs databases NR nrdb tmp
```
