### ISSUE TITLE
NR database - no node for taxid ID

### ISSUE THREAD

**Issue by catarinaloureiro** [soedinglab/MMseqs2#381]
Hi all,

I am getting started with mmseqs and tried to download the nr database with
mmseqs databases NR mmseqs2_nr tmp

However at the end of the process there are many lines like:
No node for taxID 2742838, ignoring it.
No node for taxID 2742840, ignoring it.
No node for taxID 2742841, ignoring it.
No node for taxID 2742842, ignoring it.
No node for taxID 2742843, ignoring it.
No node for taxID 2742845, ignoring it.
No node for taxID 2461416, ignoring it.

Could you let me know how to proceed here? Thanks!

**Comment by catarinaloureiro** [comment]
Hi there - was wondering if this is not the place for this question? could you let me know? thanks!

**Comment by milot-mirdita** [comment]
We were a bit busy with a paper submission.

This behavior is kind of okay and expected.
The procedure to map an NR entry to a taxonomic label is a bit involved since NCBI's NR, accession2taxid and taxdump don't match very well and it's difficult to bring them into a consistent state.

This message happens when we can parse a taxonomic identifier either by looking the accession up in one of the accession2taxid files, but the taxonomic identifier is not contained in the taxdump anymore. In this case we either try to take the taxonomic identifier of the next sequence that was clustered into this entry or leave this entry unannotated (thus it cannot contribute to LCA computation despite being findable through searching).

For nearly all sequences the mapping procedure works correctly (331375261 vs 331433500) the last 50K entries are however kind of tricky and we don't have a good solution yet to get a taxonomic identifier automatically for those.
