### ISSUE TITLE
Createtaxdb issue from ncbi nr database

### ISSUE THREAD

**Issue by jaiganeshjg** [soedinglab/MMseqs2#431]
##Command
mmseqs createtaxdb nr.fnaDB tmp --ncbi-tax-dump taxonomy/ --tax-mapping-file nr.fna.taxidmapping

## Current Behavior
Create directory tmp
createtaxdb nr.fnaDB tmp --ncbi-tax-dump taxonomy/ --tax-mapping-file ../../taxdb/nr.fna.taxidmapping

MMseqs Version:         5daca424b162cc5fdf0b9cd151aebed86975cbf6
NCBI tax dump directory taxonomy/
Taxonomy mapping file   ../../taxdb/nr.fna.taxidmapping
Taxonomy mapping mode   0
Taxonomy db mode        1
Threads                 12
Verbosity               3

Loading nodes file ... Done, got 2317712 nodes
Loading merged file ... Done, added 62177 merged nodes.
Loading names file ... Done
Init RMQ ...Done
tmp/createindex.sh: line 102: 25801 Killed                  awk 'NR == FNR { f[$1] = $2; next } $2 in f { print $1"\t"f[$2] }' "$MAPPINGFILE" "${TAXDBNAME}.lookup" > "${TAXDBNAME}_mapping"

**Comment by milot-mirdita** [comment]
How much RAM does your server have? It seems like it ran out of RAM during construction of the database.

You can try creating a NR with the `databases` command, it uses a slightly more efficient procedure than `createtaxdb` to create this mapping.

**Comment by jaiganeshjg** [comment]
Hi,
Thanks for your quick response. Anyhow the server had 35GB free memory.
Meanwhile we will try downloading the database using the database command.

Thanks!

**Comment by milot-mirdita** [comment]
The NR might be still too large for this machine. Let us know how it goes though.

**Comment by kassammohamed** [comment]
Hi I would like to use NR/NT for taxonomy assignment for some CDS in faa and fna.
I checked in the docs it is not mentioned for taxonomy but would like to know if that possible?

Thx

**Comment by milot-mirdita** [comment]
Searching against the NR works with any query type.
For nucleotide searches against the NR you should be a bit mindful of the new `--orf-filter` parameter, which can be a bit overaggressive for short reads. For anything longer than a few hundred base pairs this parameter can be ignored though.

The NT is a bit difficult to setup, we don't have an automated script yet and the the taxonomic identity is determined by top-hit (or top-equally-scoring-best-hits) instead of LCA currently. We plan to improve both setup and the taxonomic assignment procedure for nucleotide target databases in the future.

**Comment by jwasmuth** [comment]
I get the same error (v 13.45111). I'm trying to createtaxdb with 31m sequences. I am using a compute node with 3TB RAM available.

> tmp/createindex.sh: line 102: 1816922 Killed                  awk 'NR == FNR { f[$1] = $2; next } $2 in f { print $1"\t"f[$2] }' "$MAPPINGFILE" "${TAXDBNAME}.lookup" > "${TAXDBNAME}_mapping"
