### ISSUE TITLE
Convert BLAST databases to mmseq2 databases

### ISSUE THREAD

**Issue by ChristophKnapp** [soedinglab/MMseqs2#47]
Hi,
We are thinking about setting up mmseq2 as alternative to blast. I can convert blast databases to fasta files and create the corresponding mmseq databases from it but I was wondering if someone already wrote a script which is doing this and is willing to share it here?

That would save me a lot of trouble and I believe would be helpful to others as well.

All the best 

Christoph

**Comment by milot-mirdita** [comment]
Dear Christoph,

This can be somewhat dangerous, since blast databases can be masked during their creation. MMseqs2 does its own masking using the TanTan masker. Masking again might degrade sensitivity.

If you are sure that the original sequences are available in your blast database, then you can use this command to convert a blast db to fasta:
```
blastdbcmd -entry all -db [blast_database] -out [blast_database].fasta
```

Then you can convert this fasta with `mmmseqs createdb` again.

Best regards,

Milot
