### ISSUE TITLE
cluster fails when "--wrapped-scoring 1" is called due to rescore-mode despite it being specified

### ISSUE THREAD

**Issue by Zheludev** [soedinglab/MMseqs2#509]
Hello, 

I am trying to cluster some nucleotide sequences that are circularly permuted. To this end, I am calling `--wrapped-scoring 1` but am encountering a problem (that does not happen when `--wrapped-scoring 1` is omitted) that seems to be due to the `--rescore-mode`.

Here's an example command:
`mmseqs cluster perm_DB wrapped_perm_DB_clu tmp --rescore-mode 0 --min-seq-id 0.8 --wrapped-scoring 1`

it fails at a `rescorediagonal` step, citing: `ERROR: wrapped scoring is only allowed with RESCORE_MODE_HAMMING`

Further, specifying `--rescore-mode 0` (which should be the hamming mode) does not fix the issue, indeed, none of the `--rescore-modes` appear to help.

Here's an example full output of the above command being run: https://gist.github.com/Zheludev/f567fdad8ea7d2761ec4fab681b211a5

This error does not occur when `mmseqs linclust --wrapped-scoring 1` is used, but in a test case, the `linclust` seems to lack the sensitivity I require - successfully clustering some permuted sequences together but not all, even if all permutations retain 100% sequence identity (upping the `--kmer-per-seq` 100x doesn't help either)..

I am running this on linux with ample resources and on version 13.45111

I would greatly appreciate any help with this issue,

Thanks

IZ

**Comment by AnnSeidel** [comment]
Sorry for the late reply. Using wrapped-scoring was originally only supported with `RESCORE_MODE_HAMMING` by now, it should work with all rescore modes, but the error message you have mentioned was unfortunately left in. At that point in the code, `rescorediagonal` is always called with `RESCORE_MODE_ALIGNMENT`, whereas linclust always calls rescorediagonal with `RESCORE_MODE_HAMMING`, which is why you did not see this issue using linclulst. I have removed the error message now. Can you check again with the latest version (bfc6f85)?

**Comment by Zheludev** [comment]
Hi AnnSeidel,

Thanks for getting back to me. I've checked on the latest version (bfc6f85) and it works!

Thanks for making this change!

IZ
