### ISSUE TITLE
Metaclust getting smaller and smaller

### ISSUE THREAD

**Issue by kad-ecoli** [soedinglab/MMseqs2#54]
Metaclust, a database clustered by linclust protocol in MMseqs2, is becoming smaller with each release. Metaclust95 2017_01 has 97G.
Metaclust 2017_05 has 60G.
Metaclust 2018_01 has 28G only.
Shouldn't the number of Metaclust entries increase with time?

**Comment by kad-ecoli** [comment]
Seems the file size is updated.

**Comment by martin-steinegger** [comment]
Thanks for your report. I copied a wrong file to the Metaclust 2018_01 release. It should be fixed now. 
Information on the current release can be found here https://www.biorxiv.org/content/early/2018/01/05/104034.full.pdf+html. 

The input set size of the Metaclust did not increase since the first release. The data is seen as proof of concept for Linclust.  We can not commit to such a data intensive procedure at this point. It took weeks to download the full dataset used in this study. 

We believe that a sequence database based on metagenomic sequences should be offered rather by institutions such as EMBL, NCBI, the JGI or Argonne National Lab who have direct access to huge amounts of metagenomic data.
