### ISSUE TITLE
Any tips for clustering a large protein database?

### ISSUE THREAD

**Issue by hmms117** [soedinglab/MMseqs2#596]
Hi

I am doing a hierarchcal clustering of a protein database - clustering all proteins down to 95% representatives, then clustering the 95% representatives to 80% id, then to 70% and so forth. Based on recommendations, I am using the easy-linclust steps to 80% id, then switching to the easy-cluster mode.

The linclust steps are lightning fast, but when switching to easy-cluster the process stops at the prefilter stage for 10 days -with the below parameters. How can I speed up the easy-cluster steps and still ensure "quality" clusters that respect the percent ID cut off?

Many thanks for any tips!

## Steps to Reproduce (for bugs)

Command:
```
REASSIGN=TRUE mmseqs easy-cluster --min-seq-id 0.70  --cluster-reassign 1 -c 0.8 -s 6 --cov-mode 1 --alignment-mode 3 --similarity-type 2 --max-seq-len 2001 --threads 96 --split-memory-limit 750G --remove-tmp-files -v 2 proteins80.fasta proteins70.mm tmp
```
Running on local SSD, so IO should be fast. Still running fine, producing files in clu_tmp:

`pref_step2_tmp_0.index.58`

 
## Your Environment
MMseqs2 Version: 1c739ae79a0f96f5f9e28f49dae9343d69be7a3d
Statically compiled, AVX2 version
Server has 1Tb mem and using 96 threads. Running Ubuntu 18.04.

**Comment by milot-mirdita** [comment]
Since you are doing your own cascaded clustering you could disable MMseqs2's own cascaded clustering by running with `--single-step-clustering`. Then you also don't need to specify `--cluster-reassign 1` anymore. You can lower sensitivity for higher sequence identities. The following parameters might work: `-s 4 --min-seq-id 0.7 --min-ungapped-score 45`, `-s 6 --min-seq-id 0.5 --min-ungapped-score 45` `-s 7.5 --min-seq-id 0.3`.

**Comment by hmms117** [comment]
Thanks a lot for the tips - I will try these steps. The process seems stuck at the prefiltering step - I guess lowering sensitivity will speed that step up.
