### ISSUE TITLE
“mmseqs” cannot be opened because the developer cannot be verified. (OS X)

### ISSUE THREAD

**Issue by traviswheeler** [soedinglab/MMseqs2#864]
When running the latest statically compiled version of mmseqs, I receive an error because the software isn't signed.

- I am using a Macbook Pro, with Mac OS Sonoma 14.5
- Download mmseqs-osx-universal.tar.gz from https://github.com/soedinglab/MMseqs2/releases/tag/15-6f452
- Unzip and mv bin/mmseqs binary to ~/bin
- When I run the command `mmseqs`, I receive a popup with the text
```
“mmseqs” cannot be opened because the developer cannot be verified.
```
and
```
macOS cannot verify that this app is free from malware.
```

This can be resolved on the user end by following these instructions:
https://support.apple.com/en-us/102445#openanyway
(that's what I have done)

But it would be nice i the software were signed in the first place. On the developer side, these instructions are useful: https://developer.apple.com/developer-id/

**Comment by milot-mirdita** [comment]
Last I checked, it seemed like I can't sign binaries shipped in a tar.gz/zip, only in a dmg. Also it looked like the binaries need to be part of an .app and not just lose command line tools.

I didn't really want to start figuring out dmg and signing, especially since wget/curl don't add the quarantine flag.

If you wget the archive, everything works out of the box.

**Comment by milot-mirdita** [comment]
The quarantine flag can also be removed through calling:
```
xattr -d com.apple.quarantine ./mmseqs/bin/mmseqs
```

**Comment by traviswheeler** [comment]
That's helpful info, thanks!
